<a href="https://colab.research.google.com/github/Shiblu31/ML_Lab_R/blob/main/basic_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# ==== Part 1: Basic Arithmetic Operations ====
print("🔢 Basic Arithmetic Operations:")
a = 15
b = 4

print(f"Addition: {a} + {b} = {a + b}")
print(f"Subtraction: {a} - {b} = {a - b}")
print(f"Multiplication: {a} * {b} = {a * b}")
print(f"Division: {a} / {b} = {a / b}")
print(f"Integer Division: {a} // {b} = {a // b}")
print(f"Modulus: {a} % {b} = {a % b}")
print(f"Exponentiation: {a} ** {b} = {a ** b}")

print("\n" + "="*50 + "\n")

# ==== Part 2: NumPy Array Creation & Manipulation ====
print("📊 NumPy Array Creation and Manipulation:")

# Create 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr1}")

# Create 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array:\n{arr2}")

# Shape and size
print(f"Shape of arr2: {arr2.shape}")
print(f"Size of arr2: {arr2.size}")

# Array of zeros
zeros = np.zeros((2, 3))
print(f"\nZero Array:\n{zeros}")

# Array of ones
ones = np.ones((3, 2))
print(f"\nOnes Array:\n{ones}")

# Random array
random_arr = np.random.rand(2, 2)
print(f"\nRandom Array:\n{random_arr}")

# Reshape array
reshaped = arr1.reshape(5, 1)
print(f"\nReshaped arr1 to 5x1:\n{reshaped}")

# Basic operations on arrays
print(f"\nAddition of arr1 + 10: {arr1 + 10}")
print(f"Multiplication of arr1 * 2: {arr1 * 2}")
print(f"Sum of arr1: {np.sum(arr1)}")
print(f"Mean of arr1: {np.mean(arr1)}")
print(f"Max of arr2: {np.max(arr2)}")

# Transpose
print(f"\nTranspose of arr2:\n{arr2.T}")


🔢 Basic Arithmetic Operations:
Addition: 15 + 4 = 19
Subtraction: 15 - 4 = 11
Multiplication: 15 * 4 = 60
Division: 15 / 4 = 3.75
Integer Division: 15 // 4 = 3
Modulus: 15 % 4 = 3
Exponentiation: 15 ** 4 = 50625


📊 NumPy Array Creation and Manipulation:
1D Array: [1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]
Shape of arr2: (2, 3)
Size of arr2: 6

Zero Array:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

Random Array:
[[0.80436186 0.94532855]
 [0.18814995 0.08634017]]

Reshaped arr1 to 5x1:
[[1]
 [2]
 [3]
 [4]
 [5]]

Addition of arr1 + 10: [11 12 13 14 15]
Multiplication of arr1 * 2: [ 2  4  6  8 10]
Sum of arr1: 15
Mean of arr1: 3.0
Max of arr2: 6

Transpose of arr2:
[[1 4]
 [2 5]
 [3 6]]
